### ISSUE TITLE
Error when running buidler-aragon on local

### ISSUE THREAD

**Issue by blackinno** [aragon/buidler-aragon#168]
## 🐛 Bug Report
Can't start on the local and also I have tried to run with crate a new project, I've got the same error and `.aragon` is an empty folder.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/buidler-aragon/blob/master/CONTRIBUTING.md#ways-to-contribute)?

- [x] Yes

## To Reproduce

1. Clone https://github.com/mesg-foundation/aragon/tree/rename-and-migrate-version
2. Run the command `npm install` and `npm start`
3. Waiting for application build
```bash
╭─  ~/Documents/MESG/Aragon    rename-and-migrate-version               12.16.2  
╰─ npm start

> liteflow@1.0.0 start /Users/benthotsaphon/Documents/MESG/Aragon
> buidler start --show-stack-traces

main     | Starting Aragon app development...
main     | App name: liteflow-staging
main     | App id: 0x9284a8048cffd7083f16aeb285ad8c8f75211c73fd636d8648dd8cd4d67bb8a7
main     | Accounts mnemonic "explain tackle mirror kit van hammer degree position ginger unfair soup bonus"
main     | Account 0 private key 0xa8a54b2d8197bc0b19bb8a084031be71835580a01e70a45a13babd16c9bc1563
main     |            public key 0xb4124cEB3451635DAcedd11767f004d8a28c6eE7
main     | Account 1 private key 0xce8e3bda3b44269c147747a373646393b1504bfcbb73fc9564f5d753d8116608
main     |            public key 0x8401Eb5ff34cc943f096A32EF3d5113FEbE8D4Eb
main     | Account 2 private key 0x8716d2701596f51aa39d061a685d5ae5ec946eb2c7adb059d29024b5bb3b02c8
main     |            public key 0x306469457266CBBe7c0505e8Aad358622235e768
main     | Account 3 private key 0x62d7bb725787d84b059eb4950f6eea060d898183250ca3ea673a36b8e113018f
main     |            public key 0xd873F6DC68e3057e4B7da74c6b304d0eF0B484C7
main     | Account 4 private key 0x705df2ae707e25fa37ca84461ac6eb83eb4921b653e98fdc594b60bea1bb4e52
main     |            public key 0xDcC5dD922fb1D0fd0c450a0636a8cE827521f0eD
main     | Account 5 private key 0x6b12b45143fc6c7721d0ffbb9811905e773868376501fd1f46c64bf34ae29991
main     |            public key 0x27E9727FD9b8CdDdd0854F56712AD9DF647FaB74
main     | Account 6 private key 0x33f3f34569f997abb165d6967895d963a2b15ec609efcec844e65b60ee8340c7
main     |            public key 0x9766D2e7FFde358AD0A40BB87c4B88D9FAC3F4dd
main     | Account 7 private key 0x5a013cc48f0a3196b0986fc7a7a9dd320ac75e89e33302a7ff4ea6b9dc4f7b00
main     |            public key 0xBd7055AB500cD1b0b0B14c82BdBe83ADCc2e8D06
main     | Account 8 private key 0x418cc0b07bfef998f577384b185b97ad544204b5be43ac9b3abf16db2012ab5c
main     |            public key 0xe8898A4E589457D979Da4d1BDc35eC2aaf5a3f8E
main     | Account 9 private key 0x698eece6f9915b08b4d1a63958dc4f3996ee5a8d685b29d17c28beab912a77cd
main     |            public key 0xED6A91b1CFaae9882875614170CbC989fc5EfBF0
main     | 
backend  | Compiling contracts...
All contracts have already been compiled, skipping compilation.
backend  | Contracts compiled.
backend  | Started a ganache testnet instance with id 1590723844536.
backend  | Deploying Aragon bases (ENS, DAOFactory, and APM)...
backend  | ENS deployed: 0x5f6F7E8cc7346a11ca2dEf8f827b7a0b612c56a1
backend  | DAO factory deployed: 0x8EEaea23686c319133a7cC110b840d1591d9AeE0
backend  | APM deployed: 0xA53dE0b8e08b798f975D57f48384C177D410d170
backend  | Deploying DAO and app repository...
backend  | DAO deployed: 0x0D13999edC23D3475Ed3FE22a15Cc7828FeCD762
backend  | postDao | > Agent app installed: 0xA1A7d254552BEB05f15522EeD93B54441E61d1d9
backend  | postDao | > Minime token deployed: 0xf1f8AAc64036cdd399886b1C157B7e3b361093F3
backend  | postDao | > Change minime controller to token app
backend  | postDao | > token app installed: 0xA1A7d254552BEB05f15522EeD93B54441E61d1d9
backend  | postDao | > voting app installed: 0xA1A7d254552BEB05f15522EeD93B54441E61d1d9
backend  | Creating app...
backend  | Proxy address: 0x8f1cf28DCD72f5CF75091E61BF99f7Ac2edb9DAC
backend  | Repo address: 0x173ab5B15A32b71eC500FCb8e74d006071E24CBF
backend  | Implementation address: 0x8A9De741d145f076EF9814A9A39EfAd418cB4265
backend  | App version: 1,0,0
backend  | Initializing proxy...
backend  | Proxy initialized: true
backend  | postInit | > MINT_ROLE assigned to 0xb4124cEB3451635DAcedd11767f004d8a28c6eE7
backend  | postInit | > CREATE_VOTES_ROLE assigned to 0xA1A7d254552BEB05f15522EeD93B54441E61d1d9
backend  | All permissions set openly.
frontend | Generating app artifacts...
frontend | Building front end (takes a minute)...
frontend | Watching changes on front end...
frontend | Checking Aragon client...
frontend | Installing client version 775edd606333a111eb2693df53900039722a95dc locally (takes a couple of minutes)...
frontend |   cloning...
frontend |   checking out version...
frontend |   installing...
frontend |   building...
Error in plugin @aragon/buidler-aragon: There was an error while installing the Aragon client in /Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc. Please make sure that this folder is deleted and try again. 
 Error: Command failed with exit code 1: npm run build:local
child_process.js:669
    throw err;
    ^

Error: Command failed: parcel build src/index.html --out-dir ./build --public-url ./ --no-cache
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.<anonymous> (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/scripts/build-local:21:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 78802,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aragon@0.8.3 build:local: `node scripts/build-local`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aragon@0.8.3 build:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benthotsaphon/.npm/_logs/2020-05-29T03_46_54_241Z-debug.log

> aragon@0.8.3 build:local /Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc
> node scripts/build-local


aragonUI assets copied to build/aragon-ui
🚨  /Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/src/index.js: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
    "dirname": "/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc",
    "ownPass": false,
    "file": {
      "request": "@babel/plugin-proposal-class-properties",
      "resolved": "/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
    }
  },
  {
    "alias": "base$3",
    "options": {
      "spec": false,
      "loose": false,
      "useBuiltIns": true
    },
    "dirname": "/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc",
    "ownPass": false
  }
]
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
    "dirname": "/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc",
    "ownPass": false,
    "file": {
      "request": "@babel/plugin-proposal-class-properties",
      "resolved": "/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
    }
  },
  {
    "alias": "base$3",
    "options": {
      "spec": false,
      "loose": false,
      "useBuiltIns": true
    },
    "dirname": "/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc",
    "ownPass": false
  }
]
    at assertNoDuplicates (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/core/lib/config/config-descriptors.js:206:13)
    at createDescriptors (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
    at createPluginDescriptors (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at /Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/core/lib/config/config-descriptors.js:63:53
    at cachedFunction (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/gensync/index.js:244:28)
    at sync (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/gensync/index.js:84:14)
    at plugins (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/Users/benthotsaphon/.aragon/client-775edd606333a111eb2693df53900039722a95dc/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at makeError (/Users/benthotsaphon/Documents/MESG/Aragon/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/benthotsaphon/Documents/MESG/Aragon/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.installAragonClientIfNeeded (/Users/benthotsaphon/Documents/MESG/Aragon/node_modules/@aragon/buidler-aragon/src/tasks/start/client/aragon-client.ts:39:7)
    at Object.startClient (/Users/benthotsaphon/Documents/MESG/Aragon/node_modules/@aragon/buidler-aragon/src/tasks/start/start-client.ts:27:3)
    at SimpleTaskDefinition.action (/Users/benthotsaphon/Documents/MESG/Aragon/node_modules/@aragon/buidler-aragon/src/tasks/start-task.ts:92:38)
    at Environment._runTaskDefinition (/Users/benthotsaphon/Documents/MESG/Aragon/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:196:14)
    at main (/Users/benthotsaphon/Documents/MESG/Aragon/node_modules/@nomiclabs/buidler/src/internal/cli/cli.ts:151:5)

```
## Expected behavior

Can start on the local network 

## Actual Behavior
Can't build front-end like the Error display 

#### Network and buidler.config?

local network

#### Aragon app project?

Github Url: https://github.com/mesg-foundation/aragon/tree/rename-and-migrate-version

#### Environment

- macOS Catalina version 10.15.5
- NodeJS: `12.16.2` and builder: `0.2.6`

Issues on repository https://github.com/mesg-foundation/aragon/issues/37

**Comment by 0xGabi** [comment]
Hi @blackinno I open a PR on your repo that should fix this: https://github.com/mesg-foundation/aragon/pull/38

It seems related with the recent babel release a couple of days ago: https://github.com/babel/babel/releases

**Comment by blackinno** [comment]
@0xGabi Thank you for your answer, the version of babel isn't resolved the issue I test and I've got the same issue.

**Comment by dapplion** [comment]
I've experienced the same issue building the client through the buidler-plugin, but it builds fine doing the build directly.

**Comment by sohkai** [comment]
@dapplion Yes, cloning and building locally with `yarn` will work, because of the `yarn.lock` locking the babel dependencies.

This will be fixed soon!

**Comment by 0xGabi** [comment]
Hey, @blackinno @dapplion apologies for the delay on address this issue. I just [release a new version of the plugin](https://github.com/aragon/buidler-aragon/releases/tag/v0.2.8) that does a hotfix of the problem. 

Note we are still looking into the root cause to support once again the latest version of the client on local development. It results to be a much harder bug to solve.

**Comment by sohkai** [comment]
Closing for now; we've hotfixed the problem and will continue looking into it in `aragon/aragon`.

**Comment by jomarip** [comment]
Just an update. I had this issue today.
